### ISSUE TITLE
Update React-bootstrap

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/stein-saks-papir#310]
@mrbrianevans

This package needs to be updated.

Remember to check for visual bugs before submitting a PR.

**Comment by mrbrianevans** [comment]
Please assign me to the issue, thanks

**Comment by w3bdesign** [comment]
@mrbrianevans 

Assigned.

**Comment by mrbrianevans** [comment]
This test fails after the upgrade:
```javascript

  test('Velg et våpen flere ganger og se at knappene skjules', async () => {
    // Vi bruker en array og forEach for å klikke 10 ganger
    const repeatClickTenTimes = Array.from({ length: 10 }, (_v, i) => i);

    render(<App />);

    await waitFor(() => {
      repeatClickTenTimes.forEach(() => userEvent.click(screen.queryByRole('button', { name: /stein/i })));
    });
    expect(screen.queryByRole('button', { name: /stein/i })).toBeNull();
  });
```

Will investigate what update to the library causes this behaviour to change.

`CardDeck` has been replaced with `CardGroup`

**Comment by w3bdesign** [comment]
@mrbrianevans 

If you paste the error message, I will see if I can help if you need help.
